### ISSUE TITLE
Compilation error on debian

### ISSUE THREAD

**Issue by ArturHarasimiuk** [intel/gmmlib#7]
original issue: https://github.com/intel/compute-runtime/issues/16

When compiling on debian buster, using clang 5.0.1-2, the make step give me:
```
Scanning dependencies of target igfx_gmmumd_excite
[  1%] Building CXX object gmmlib/Source/GmmLib/CMakeFiles/igfx_gmmumd_excite.dir/__/Common/AssertTracer/AssertTracer.cpp.o
clang: error: unknown argument: '-fno-tree-pre'
clang: warning: -Wl,--no-undefined: 'linker' input unused [-Wunused-command-line-argument]
```

**Comment by drprajap** [comment]
Fixed the issue - [ccbea3e](https://github.com/intel/gmmlib/commit/ccbea3e0be09e2718544a0c129cd878079c558c0), verified gmmlib build using clang 5.0.
